Phase 1: Wallet
fidelity: Defines the new fidelity API of the Wallet. Give it a fresh look.
Comparing it with the previous version won't be useful.

storage: Stores the fidelity bonds in wallet storage. Also removes the redundant FileData
interface. wallet storage is now directly encoded into the wallet file.

direct_send: Add anti-feesnipping locktime and disaalow fidelity bond related operation
via direct send.

error: Add a bunch of internal error type + new fidelity error type.

rpc: Update the scan logic for relevant fidelity parts. Using the new fidelity
structures in the wallet store.

api: Minor changes in previous wallet apis due to fidelity addition.